builder:
  track: dev

labels:
  app: estafette-extension-gke
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  build:
    image: golang:1.11.1-alpine3.8
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - go build -a -installsuffix cgo -ldflags "-X main.app=${ESTAFETTE_LABEL_APP} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: extensions/docker:dev
    action: build
    container: gke
    repositories:
    - extensions
    path: ./publish
    copy:
    - templates

  test-alpha-version:
    image: extensions/gke:${ESTAFETTE_BUILD_VERSION}
    retries: 1
    credentials: gke-tooling
    app: gke
    namespace: estafette
    visibility: private
    container:
      repository: extensions
      name: gke
      tag: alpha
      port: 5000
      env:
        MY_CUSTOM_ENV: value1
        MY_OTHER_CUSTOM_ENV: value2
      cpu:
        request: 100m
        limit: 100m
      memory:
        request: 256Mi
        limit: 256Mi
      liveness:
        path: /liveness
        delay: 30
        timeout: 1
      readiness:
        path: /readiness
        delay: 30
        timeout: 1
    autoscale:
      min: 3
      max: 50
      cpu: 80
    hosts:
    - gke.estafette.io
    - gke-deploy.estafette.io
    dryrun: true

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: gke
    repositories:
    - extensions
    tags:
    - dev

releases:
  beta:
    stages:
      tag-container-image:
        image: extensions/docker:stable
        action: tag
        container: gke
        repositories:
        - extensions
        tags:
        - beta

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:stable
        action: tag
        container: gke
        repositories:
        - extensions
        tags:
        - stable
        - latest