apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-secrets
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
type: Opaque
data:
  {{- range $key, $value := .Secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}