apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range .Labels}}
    {{.Key}}: {{.Value}}
    {{end}}
  annotations:
    estafette.io/letsencrypt-certificate: "true"
    estafette.io/letsencrypt-certificate-hostnames: "{{.Hosts}}"
type: Opaque