apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-letsencrypt-certificate
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
    type: letsencrypt-certificate
  annotations:
    estafette.io/letsencrypt-certificate: "true"
    estafette.io/letsencrypt-certificate-hostnames: "{{.AllHostsJoined}}"
type: Opaque