apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}-config
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
data:
  {{- range $filename, $filecontent := .ConfigmapFiles}}
  {{$filename}}: |-
  {{- $filecontent | indent 4}}
  {{- end}}