apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}-configs
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
data:
  {{- range $filename, $filecontent := .ConfigmapFiles}}
  {{$filename}}: |-
{{$filecontent | indent 4}}
  {{- end}}