apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{.NameWithTrack}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.NameWithTrack}}
  minReplicas: {{.MinReplicas}}
  maxReplicas: {{.MaxReplicas}}
  targetCPUUtilizationPercentage: {{.TargetCPUPercentage}}