apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range .Labels}}
    {{.Key}}: {{.Value}}
    {{end}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Name}}
  minReplicas: {{.MinPods}}
  maxReplicas: {{.MaxPods}}
  targetCPUUtilizationPercentage: {{.TargetCPU}}