apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Name}}-internal
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{.NginxIngressProxyBodySize}}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{.NginxIngressProxyConnectTimeout}}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{.NginxIngressProxySendTimeout}}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{.NginxIngressProxyReadTimeout}}"
    # estafette.io/google-cloud-dns: "true"
    # estafette.io/google-cloud-dns-hostnames: "{{.InternalHostsJoined}}"
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "false"
    estafette.io/cloudflare-hostnames: "{{.InternalHostsJoined}}"
spec:
  tls:
  - hosts:
    {{- range .InternalHosts}}
    - {{.}}
    {{- end}}
  rules:
  {{- range .InternalHosts}}
  - host: {{.}}
    http:
      paths:
      - path: {{$.InternalIngressPath}}
        backend:
          serviceName: {{$.Name}}
          servicePort: https
  {{- end}}