apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range .Labels}}
    {{.Key}}: {{.Value}}
    {{end}}



---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: estafette-ci-web
  namespace: estafette
  labels:
    app: estafette-ci-web
    team: tooling
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "${ALLOW_INGRESS_OFFICES}"
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "true"
    estafette.io/cloudflare-hostnames: "${HOSTNAMES}"
spec:
  tls:
  - hosts:
    - ${HOSTNAMES}
    secretName: estafette-ci-web-letsencrypt-certificate
  rules:
  - host: ${HOSTNAMES}
    http:
      paths:
      - path: /
        backend:
          serviceName: estafette-ci-web
          servicePort: https