apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Name}}-internal
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    estafette.io/google-cloud-dns: "true"
    estafette.io/google-cloud-dns-hostnames: "{{.InternalHostsJoined}}"
spec:
  tls:
  - hosts:
    {{- range .InternalHosts}}
    - {{.}}
    {{- end}}
  rules:
  {{- range .InternalHosts}}
  - host: {{.}}
    http:
      paths:
      - path: {{$.IngressPath}}
        backend:
          serviceName: {{$.Name}}
          servicePort: https
  {{- end}}