apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        {{- range $key, $value := .Labels}}
        {{$key}}: {{$value}}
        {{- end}}
        version: {{.BuildVersion}}
        {{- if .IncludeReleaseIDLabel}}
        release-id: "{{.ReleaseIDLabel}}"
        {{- end}}
      annotations:
        prometheus.io/scrape: "{{.Container.Metrics.Scrape}}"
        prometheus.io/path: "{{.Container.Metrics.Path}}"
        prometheus.io/port: "{{.Container.Metrics.Port}}"
        prometheus.io/scrape-nginx-sidecar: "true"
    spec:
      restartPolicy: OnFailure
      serviceAccount: {{.Name}}
      containers:
      - name: {{.Name}}
        image: {{.Container.Repository}}/{{.Container.Name}}:{{.Container.Tag}}
        imagePullPolicy: IfNotPresent
        {{- if .Container.EnvironmentVariables }}
        env:
        {{- range $key, $value := .Container.EnvironmentVariables }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{.Container.CPURequest}}
            memory: {{.Container.MemoryRequest}}
          limits:
            cpu: {{.Container.CPULimit}}
            memory: {{.Container.MemoryLimit}}
        {{- if or .MountApplicationSecrets .MountConfigmap .MountAdditionalVolumes }}
        volumeMounts:
        {{- if .MountApplicationSecrets }}
        - name: app-secrets
          mountPath: {{.SecretMountPath}}
        {{- end }}
        {{- if .MountConfigmap }}
        - name: app-configs
          mountPath: {{.ConfigMountPath}}
        {{- end }}
        {{- range .AdditionalVolumeMounts}}
        - name: {{.Name}}
          mountPath: {{.MountPath}}
        {{- end}}
        {{- end }}
      terminationGracePeriodSeconds: 300
      volumes:
      {{- if .MountApplicationSecrets }}
      - name: app-secrets
        secret:
          secretName: {{.Name}}-secrets
      {{- end }}
      {{- if .MountConfigmap }}
      - name: app-configs
        configMap:
          name: {{.Name}}-configs
      {{- end }}
      {{- range .AdditionalVolumeMounts}}
      - name: {{.Name}}
{{.VolumeYAML | indent 8}}
      {{- end}}