apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range .Labels}}
    {{.Key}}: {{.Value}}
    {{end}}
type: Opaque


apiVersion: v1
kind: Secret
metadata:
  name: estafette-ci-web-letsencrypt-certificate
  namespace: estafette
  labels:
    app: estafette-ci-web
    team: tooling
  annotations:
    estafette.io/letsencrypt-certificate: "true"
    estafette.io/letsencrypt-certificate-hostnames: "${HOSTNAMES}"
type: Opaque