apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{range .Labels}}
    {{.Key}}: {{.Value}}
    {{end}}
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
spec:
  type: {{.ServiceType}}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: {{.AppLabelSelector}}

---
apiVersion: v1
kind: Service
metadata:
  name: estafette-ci-web
  namespace: estafette
  labels:
    app: estafette-ci-web
    team: tooling
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "/robots.txt"
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: estafette-ci-web
